@startuml

abstract class BaseService<T> {
    #Repository : IRepository<T>
    #_unitOfWork : IUnitOfWork

    +DeleteAsync(object id) : Task<bool>
}

class FormService {}

' Entity

' ViewModel

' Service Layer


' Controller
class FormController {
    +DeleteForm(Guid id) : Task<ActionResult>
}

' Relationships (with comments on arrows)
FormService --|> BaseService : "inherits default implementations"
FormController --> FormService : "deletes form"

@enduml