@startuml
class IssueTicketRepository {
    + IssueTicketRepository(context:DPMSContext)
}
class "BaseRepository`1"<T> {
}
"BaseRepository`1" "<IssueTicket>" <|-- IssueTicketRepository
IIssueTicketRepository <|-- IssueTicketRepository
@enduml
