@startuml
class AccountCredentialsVM {
    + FullName : string <<get>> <<set>>
    + UserName : string <<get>> <<set>>
    + Password : string <<get>> <<set>>
    + Email : string <<get>> <<set>>
    + RoleName : string <<get>> <<set>>
    + DpmsLoginUrl : string <<get>> <<set>>
}
@enduml
