@startuml
actor Admin
boundary "System Detail Page" as Screen
participant "ExternalSystemController" as Controller
participant "ExternalSystemService" as Service
participant "ExternalSystemRepository" as Repo
database "Database" as DB

Admin -> Screen : Open External System detail
activate Screen
Screen -> Controller : GetSystemDetails(systemId)
deactivate Screen
activate Controller

Controller -> Service : GetExternalSystemDetailAsync(systemId)
activate Service

Service -> Repo : GetDetailAsync(systemId, includes: Groups, Users, Purposes)
activate Repo
Repo -> DB : Invoke SELECT query
DB --> Repo : ExternalSystem + Users + Groups + Purposes
Repo --> Service : Aggregated data
deactivate Repo


Service --> Controller : Return ExternalSystemDetailVM
deactivate Service

Controller --> Screen : Display external system detail
deactivate Controller
@enduml
