@startuml
class PasswordUtils {
    + {static} HashPassword(password:string, salt:string) : string
    + {static} GenerateSalt(saltSize:int) : byte[]
    + {static} GeneratePassword(numUppercase:int, numLowercase:int, numNumeric:int) : string
}
@enduml
