@startuml
class ExternalSystem {
    + Name : string? <<get>> <<set>>
    + Description : string? <<get>> <<set>>
}
BaseModel <|-- ExternalSystem
ExternalSystem --> "Status" ExternalSystemStatus
@enduml
