@startuml
class FormElement {
    + FormId : string? <<get>> <<set>>
    + ParentId : string? <<get>> <<set>>
    + Name : string? <<get>> <<set>>
    + OrderIndex : int? <<get>> <<set>> = 0
}
BaseModel <|-- FormElement
FormElement --> "DataType" FormElementTypes
FormElement --> "Form" Form
FormElement --> "Parent" FormElement
@enduml
