@startuml
class LoggingInterceptorService {
    + LoggingInterceptorService(logContext:DPMSLoggingContext, logger:ILogger<LoggingInterceptorService>)
    + OnRequestAsync(logContext:HttpLoggingInterceptorContext) : ValueTask
    + OnResponseAsync(logContext:HttpLoggingInterceptorContext) : ValueTask
}
IHttpLoggingInterceptor <|-- LoggingInterceptorService
@enduml
