@startuml
class ForgotpasswordController {
    + ForgotpasswordController(emailService:IEmailService, authService:AuthService, userService:IUserService)
    + <<async>> ForgotPassword(resetPasswordRequest:ForgotPasswordRequest?) : Task<ActionResult<bool>>
    + VerifyResetToken(token:string) : IActionResult
    + <<async>> SetNewPassword(model:ResetPasswordModel) : Task<IActionResult>
}
ControllerBase <|-- ForgotpasswordController
@enduml
