@startuml
class PolicyRequirement {
    + PolicyRequirement(policyName:string)
    + IsAuthenticatedPolicy : bool <<get>>
    + IsFeatureRequiredPolicy : bool <<get>>
}
IAuthorizationRequirement <|-- PolicyRequirement
@enduml
